language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
jobs:
  include:
    - stage: tests
      script: pnpm run lint
      script: pnpm run test
      script: pnpm run test:coverage
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - pnpx semantic-release
