language: node_js
node_js:
  - "lts/*"
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
services:
  - docker
jobs:
  include:
    - stage: "Tests"
      name: "Unit tests"
      script: pnpm run test
    - name: "Submit test coverage"
      script: pnpm run test:coverage
    - name: "Lint"
      script: pnpm run lint
    - stage: "Build"
      name: "Build Docker Image"
      deploy:
        provider: script
        skip_cleanup: true
        script: docker build -t dicediscord/bot .
    - stage: "Release"
      name: "Semantic Release"
      deploy:
        provider: script
        skip_cleanup: true
        script: pnpx semantic-release
