version: '3.7'
services:
  bot:
    image: dice-discord/bot
    restart: always
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
