version: '3.7'
services:
  bot:
    image: dicediscord/bot
    restart: always
    env_file: .env
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
