version: '3.7'
services:
  bot:
    image: dicediscord/bot
    restart: always
    env_file: .env
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  dd-agent:
    image: datadog/agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent-conf.d:/conf.d:ro
    env_file: .env
